In [1]:
from scipy.linalg import pascal 
n = 5 
pascal = pascal(n,kind='lower')
print(pascal)

[[1 0 0 0 0]
 [1 1 0 0 0]
 [1 2 1 0 0]
 [1 3 3 1 0]
 [1 4 6 4 1]]


In [2]:
n = 10 
for i in range(n):
    print(' '*(n-i), end='')
    print(' '.join(map(str, str(11**i))))

          1
         1 1
        1 2 1
       1 3 3 1
      1 4 6 4 1
     1 6 1 0 5 1
    1 7 7 1 5 6 1
   1 9 4 8 7 1 7 1
  2 1 4 3 5 8 8 8 1
 2 3 5 7 9 4 7 6 9 1


In [4]:
import numpy as np 

In [5]:
n = 10
pascal = np.zeros((n, n), dtype=int)
pascal[0, 0] = pascal[1, 0] = pascal[1, 1] = 1
for row in range(2, n):
    for col in range(0, row+1):
        pascal[row, col] = pascal[row-1, col-1] + pascal[row-1, col]
        print(pascal)

[[1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 2 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 2 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 2 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 2 1 0 0 0 0 0 0 0]
 [1 3 0